Repository storm-fsv-cvut/smoderp2d, pull requests merged in 2024-05, with the labels that each got.

#372 courant.courant: speedup
  smoderp2d/courant.py
Labels: enhancement

#374 courant.courant: use system Python functions instead of numpy where p…
  smoderp2d/courant.py
Labels: enhancement

#376 data_preparation._get_a: optimize algorithm
  smoderp2d/providers/base/data_preparation.py
Labels: enhancement

#373 runoff.run: avoid arrays in time comparison check
  smoderp2d/runoff.py
Labels: enhancement

#377 runoff: avoid ma() for time checks where possible
  smoderp2d/runoff.py
Labels: enhancement

#380 cumulative_max: simplify conditions to maximum() operations
  smoderp2d/core/cumulative_max.py
Labels: enhancement

#381 removeCellsWithSameHeightNeighborhood: avoid looped point_m checks
  smoderp2d/flow_algorithm/py_dmtfce.py
Labels: enhancement

#382 removeCellsWithSameHeightNeighborhood: avoid third-generation loop
  smoderp2d/flow_algorithm/py_dmtfce.py
Labels: enhancement

#386 QGIS plugin: be less verbose about historical items for which the loading failed
  bin/qgis/smoderp2d-plugin/smoderp_2D_dockwidget.py
Labels: QGIS

#379 runoff: newtime and oldtime computation - avoid Sisyphos work
  smoderp2d/runoff.py
  tests/data/reference/test_rill/control/massbalance.asc
  tests/data/reference/test_rill/control_point/point001.csv
  tests/data/reference/test_rill/control_point/point002.csv
  tests/data/reference/test_rill/control_point/point003.csv
  tests/data/reference/test_rill/control_point/point004.csv
  tests/data/reference/test_rill/control_point/point007.csv
  tests/data/reference/test_rill/control_point/point008.csv
  tests/data/reference/test_sheet/control/cinfil_m3.asc
  tests/data/reference/test_sheet/control/csheetvout_m3.asc
  tests/data/reference/test_sheet/control/cvin_m3.asc
  tests/data/reference/test_sheet/control/massbalance.asc
  tests/data/reference/test_sheet/control/mqsheet_m3_s.asc
  tests/data/reference/test_sheet/control/volrest_m3.asc
  tests/data/reference/test_sheet/control_point/point001.csv
  tests/data/reference/test_sheet/control_point/point002.csv
  tests/data/reference/test_sheet/control_point/point003.csv
  tests/data/reference/test_sheet/control_point/point004.csv
  tests/data/reference/test_sheet/control_point/point007.csv
  tests/data/reference/test_sheet/control_point/point008.csv
  tests/data/reference/test_sheet/cvsur_m3.asc
  tests/data/reference/test_sheet/mqsur_m3_s.asc
  tests/data/reference/test_sheet/mrsearstr_pa.asc
  tests/data/reference/test_sheet/mvel_m_s.asc
  tests/data/reference/test_sheet/mwlevel_m.asc
  tests/data/reference/test_sheet_stream/control/massbalance.asc
  tests/data/reference/test_sheet_stream/control_point/point001.csv
  tests/data/reference/test_sheet_stream/control_point/point002.csv
  tests/data/reference/test_sheet_stream/control_point/point003.csv
  tests/data/reference/test_stream_rill/control/massbalance.asc
  tests/data/reference/test_stream_rill/control_point/point001.csv
  tests/data/reference/test_stream_rill/control_point/point002.csv
  tests/data/reference/test_stream_rill/control_point/point003.csv
  tests/data/reference/test_stream_rill_mfda/control/massbalance.asc
  tests/data/reference/test_stream_rill_mfda/control_point/point001.csv
  tests/data/reference/test_stream_rill_mfda/control_point/point002.csv
  tests/data/reference/test_stream_rill_mfda/control_point/point003.csv
  tests/data/reference/test_stream_rill_mfda/control_point/point004.csv
  tests/data/reference/test_stream_rill_mfda/control_point/point007.csv
  tests/data/reference/test_stream_rill_mfda/control_point/point008.csv
  tests/data/reference/test_stream_rill_mfda/streams.csv
  tests/data/reference/test_stream_rill_mfda_diffusion/control/massbalance.asc
  tests/data/reference/test_stream_rill_mfda_diffusion/control_point/point001.csv
  tests/data/reference/test_stream_rill_mfda_diffusion/control_point/point002.csv
  tests/data/reference/test_stream_rill_mfda_diffusion/control_point/point003.csv
Labels: enhancement

#391 ArcGIS: rasterize soilveg (all touched pixels)
  smoderp2d/providers/arcgis/data_preparation.py
Labels: ArcGIS

#390 write mat arrays to temp
  smoderp2d/providers/base/data_preparation.py
Labels: data preparation

#396 streams: change from conditional import to conditional inheritance
  smoderp2d/core/surface.py
Labels: bug

#392 Batch processing
  bin/grass/batch_process.py
  bin/grass/batch_process_csv.py
  bin/qgis/smoderp2d-plugin/connect_grass.py
  bin/qgis/smoderp2d-plugin/custom_widgets.py
  bin/qgis/smoderp2d-plugin/smoderp_2D_dockwidget.py
  smoderp2d/providers/grass/__init__.py
  smoderp2d/runners/base.py
  smoderp2d/runners/grass.py
  smoderp2d/runners/qgis.py
  tests/batch/batch_process.csv
  tests/batch/batch_process_csv.bat
  tests/batch/batch_process_csv_linux.sh
  tests/batch/batch_process_single.bat
  tests/batch/batch_process_single_linux.sh
  tests/batch/init_windows_env.bat
  tests/batch/install_joblib_windows.bat
Labels: enhancement, QGIS, GRASS GIS

#402 Check for patch in GRASS 8.3
  README.md
  bin/qgis/grass_patch/core.py
  bin/qgis/smoderp2d-plugin/smoderp_2D_dockwidget.py
  smoderp2d/runners/grass.py
Labels: QGIS
