Repository storm-fsv-cvut/smoderp2d, pull requests merged in 2024-03, with the labels that each got.

#341 fix fake bifurcation detection
  smoderp2d/providers/grass/data_preparation.py
Labels: bug

#342 fix streams snapped to lines instead of points
  smoderp2d/providers/grass/data_preparation.py
Labels: bug

#344 stream_functions: solve issues with division by zero
  smoderp2d/stream_functions/stream_f.py
Labels: bug

#345 data_preparation._get_a: speedup
  smoderp2d/providers/base/data_preparation.py
Labels: data preparation

#346 fix failing QGIS with tables imported via Data Source Manager
  bin/qgis/smoderp2d-plugin/smoderp_2D_dockwidget.py
Labels: bug

#350 better handling of rainfall data errors
  smoderp2d/exceptions.py
  smoderp2d/processes/rainfall.py
  smoderp2d/providers/base/__init__.py
  smoderp2d/providers/base/data_preparation.py
  smoderp2d/providers/profile1d/__init__.py
Labels: enhancement, data preparation, QGIS
