Repository storm-fsv-cvut/smoderp2d, pull requests merged in 2024-06, with the labels that each got.

#404 Improve parallelization of batch processing
  bin/grass/batch_process.py
  bin/grass/batch_process_csv.py
  bin/grass/r.smoderp2d/r.smoderp2d.py
  bin/qgis/smoderp2d-plugin/smoderp_2D_dockwidget.py
  tests/batch/batch_process_csv.bat
  tests/batch/batch_process_csv_linux.sh
Labels: enhancement

#400 Save log messages in target directory
  bin/arcgis/SMODERP2D.pyt
  bin/arcgis/SMODERP2D.pyt.xml
  bin/grass/batch_process.py
  bin/grass/r.smoderp2d/r.smoderp2d.py
  bin/qgis/smoderp2d-plugin/smoderp_2D_dockwidget.py
  smoderp2d/providers/base/__init__.py
  smoderp2d/providers/base/data_preparation.py
  smoderp2d/runners/base.py
  smoderp2d/runners/grass.py
Labels: enhancement

#395 Update CI workflow (Python 3.12 and NumPy 1.26.4)
  .github/workflows/cmd_template.yml
  .github/workflows/grass_provider.yml
  .github/workflows/requirements.txt
  .github/workflows/requirements2.7.txt
  .github/workflows/requirements3.11.txt
  .github/workflows/requirements3.12.txt
  .github/workflows/requirements3.9.txt
Labels: tests

#411 time_step: fix h_sheet saved into rill_courant
  smoderp2d/time_step.py
  tests/data/reference/test_implicit_stream_rill_mfda/control/cinfil_m3.asc
  tests/data/reference/test_implicit_stream_rill_mfda/control/crillvout_m3.asc
  tests/data/reference/test_implicit_stream_rill_mfda/control/csheetvout_m3.asc
  tests/data/reference/test_implicit_stream_rill_mfda/control/cvin_m3.asc
  tests/data/reference/test_implicit_stream_rill_mfda/control/massbalance.asc
  tests/data/reference/test_implicit_stream_rill_mfda/control/mqrill_m3_s.asc
  tests/data/reference/test_implicit_stream_rill_mfda/control/mqsheet_m3_s.asc
  tests/data/reference/test_implicit_stream_rill_mfda/control/mwlevelrill_m.asc
  tests/data/reference/test_implicit_stream_rill_mfda/control/volrest_m3.asc
  tests/data/reference/test_implicit_stream_rill_mfda/control/widthrill.asc
  tests/data/reference/test_implicit_stream_rill_mfda/control_point/point001.csv
  tests/data/reference/test_implicit_stream_rill_mfda/control_point/point002.csv
  tests/data/reference/test_implicit_stream_rill_mfda/control_point/point003.csv
  tests/data/reference/test_implicit_stream_rill_mfda/control_point/point004.csv
  tests/data/reference/test_implicit_stream_rill_mfda/control_point/point007.csv
  tests/data/reference/test_implicit_stream_rill_mfda/control_point/point008.csv
  tests/data/reference/test_implicit_stream_rill_mfda/cvsur_m3.asc
  tests/data/reference/test_implicit_stream_rill_mfda/mqsur_m3_s.asc
  tests/data/reference/test_implicit_stream_rill_mfda/mrsearstr_pa.asc
  tests/data/reference/test_implicit_stream_rill_mfda/mvel_m_s.asc
  tests/data/reference/test_implicit_stream_rill_mfda/mwlevel_m.asc
  tests/data/reference/test_implicit_stream_rill_mfda/streams.csv
  tests/data/reference/test_rill/control/massbalance.asc
  tests/data/reference/test_rill/control_point/point001.csv
  tests/data/reference/test_rill/control_point/point002.csv
  tests/data/reference/test_rill/control_point/point003.csv
  tests/data/reference/test_rill/control_point/point004.csv
  tests/data/reference/test_rill/control_point/point007.csv
  tests/data/reference/test_rill/control_point/point008.csv
  tests/data/reference/test_sheet/control/massbalance.asc
  tests/data/reference/test_sheet/control_point/point001.csv
  tests/data/reference/test_sheet/control_point/point002.csv
  tests/data/reference/test_sheet/control_point/point003.csv
  tests/data/reference/test_sheet/control_point/point004.csv
  tests/data/reference/test_sheet/control_point/point007.csv
  tests/data/reference/test_sheet/control_point/point008.csv
  tests/data/reference/test_sheet_stream/control/massbalance.asc
  tests/data/reference/test_stream_rill/control/massbalance.asc
  tests/data/reference/test_stream_rill_mfda/control_point/point001.csv
  tests/data/reference/test_stream_rill_mfda/control_point/point002.csv
  tests/data/reference/test_stream_rill_mfda/control_point/point003.csv
  tests/data/reference/test_stream_rill_mfda_diffusion/control/massbalance.asc
  tests/data/reference/test_stream_rill_mfda_diffusion/control_point/point001.csv
  tests/data/reference/test_stream_rill_mfda_diffusion/control_point/point002.csv
  tests/data/reference/test_stream_rill_mfda_diffusion/control_point/point003.csv
Labels: bug

#412 implicit solution: fix missing subsurface parameter
  smoderp2d/time_step.py
Labels: bug

#409 Enable installing grass addon by using gextension
  bin/grass/r.smoderp2d/r.smoderp2d.html
  bin/grass/r.smoderp2d/r.smoderp2d.py
Labels: GRASS GIS
